#include <tesseract/common/macros.h>
TESSERACT_COMMON_IGNORE_WARNINGS_PUSH
#include <gtest/gtest.h>
#include <cmath>
#include <memory>
#include <string>
#include <utility>
#include <vector>
TESSERACT_COMMON_IGNORE_WARNINGS_POP

#include <tesseract_trac_ik/trac-ik/trac-ik_inv_kin_chain.h>

#include <tesseract/kinematics/kdl/kdl_fwd_kin_chain.h>
#include <tesseract/kinematics/kinematic_group.h>
#include <tesseract/kinematics/validate.h>
#include <tesseract/common/resource_locator.h>
#include <tesseract/scene_graph/graph.h>
#include <tesseract/scene_graph/joint.h>
#include <tesseract/state_solver/kdl/kdl_state_solver.h>
#include <tesseract/urdf/urdf_parser.h>

using namespace tesseract::kinematics;
using tesseract::common::JointId;
using tesseract::common::LinkId;

namespace
{
const LinkId BASE_LINK{ "base_link" };
const LinkId TIP_LINK{ "tool0" };

/**
 * Trac-IK is a time-bounded random-restart solver, so the deadline it is given is the only thing standing between a
 * solvable query and a spurious failure on a loaded machine. Tests use a deadline far above the 5 ms default and never
 * assert on solve time or on the number of solutions returned.
 */
const double TEST_MAX_TIME = 0.5;

tesseract::scene_graph::SceneGraph::UPtr getSceneGraphIIWA()
{
  tesseract::common::GeneralResourceLocator locator;
  const std::string path =
      locator.locateResource("package://tesseract/support/urdf/lbr_iiwa_14_r820.urdf")->getFilePath();
  return tesseract::urdf::parseURDFFile(path, locator);
}

/** @brief A well-conditioned configuration away from the joint limits, used as the ground truth for round trips */
Eigen::VectorXd getReferenceConfiguration()
{
  Eigen::VectorXd q(7);
  q << 0.2, 0.5, -0.3, -1.2, 0.4, 0.8, 0.1;
  return q;
}

void expectPoseNear(const Eigen::Isometry3d& target,
                    const Eigen::Isometry3d& actual,
                    double translation_tol,
                    double rotation_tol)
{
  EXPECT_LT((target.translation() - actual.translation()).norm(), translation_tol);
  EXPECT_LT(Eigen::Quaterniond(target.rotation()).angularDistance(Eigen::Quaterniond(actual.rotation())), rotation_tol);
}

/**
 * @brief Solve for a pose generated by forward kinematics and check every solution reproduces it
 *
 * The IIWA is redundant, so a round trip through forward kinematics is the only valid correctness check; the returned
 * joint values are not expected to match the configuration the pose was generated from.
 */
void expectSolvesRoundTrip(const InverseKinematics& inv_kin,
                           const ForwardKinematics& fwd_kin,
                           double translation_tol = 1e-3,
                           double rotation_tol = 1e-3)
{
  const Eigen::VectorXd q_ref = getReferenceConfiguration();
  const Eigen::Isometry3d target_pose = fwd_kin.calcFwdKin(q_ref).at(TIP_LINK);
  const Eigen::VectorXd seed = q_ref.array() + 0.1;

  const tesseract::common::LinkIdTransformMap input{ { TIP_LINK, target_pose } };
  const IKSolutions solutions = inv_kin.calcInvKin(input, seed);
  ASSERT_FALSE(solutions.empty());

  for (const auto& solution : solutions)
  {
    ASSERT_EQ(solution.size(), 7);
    expectPoseNear(target_pose, fwd_kin.calcFwdKin(solution).at(TIP_LINK), translation_tol, rotation_tol);
  }
}
}  // namespace

TEST(TesseractKinematicsUnit, TracIKInvKinAccessorsUnit)  // NOLINT
{
  auto scene_graph = getSceneGraphIIWA();
  const TracIKInvKinChain inv_kin(*scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);

  const std::vector<JointId> joint_ids{ "joint_a1", "joint_a2", "joint_a3", "joint_a4",
                                        "joint_a5", "joint_a6", "joint_a7" };

  EXPECT_EQ(inv_kin.getSolverName(), TRACIK_INV_KIN_CHAIN_SOLVER_NAME);
  EXPECT_EQ(inv_kin.numJoints(), 7);
  EXPECT_EQ(inv_kin.getJointIds(), joint_ids);
  EXPECT_EQ(inv_kin.getBaseLinkId(), BASE_LINK);
  EXPECT_EQ(inv_kin.getWorkingFrame(), BASE_LINK);
  ASSERT_EQ(inv_kin.getTipLinkIds().size(), 1);
  EXPECT_EQ(inv_kin.getTipLinkIds().front(), TIP_LINK);
}

TEST(TesseractKinematicsUnit, TracIKInvKinChainsConstructorUnit)  // NOLINT
{
  // The chain-vector constructor and the base/tip constructor must describe the same chain
  auto scene_graph = getSceneGraphIIWA();
  const std::vector<std::pair<LinkId, LinkId>> chains{ std::make_pair(BASE_LINK, TIP_LINK) };
  const TracIKInvKinChain inv_kin(*scene_graph, chains, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);

  EXPECT_EQ(inv_kin.numJoints(), 7);
  EXPECT_EQ(inv_kin.getBaseLinkId(), BASE_LINK);
  ASSERT_EQ(inv_kin.getTipLinkIds().size(), 1);
  EXPECT_EQ(inv_kin.getTipLinkIds().front(), TIP_LINK);

  const KDLFwdKinChain fwd_kin(*scene_graph, BASE_LINK, TIP_LINK);
  expectSolvesRoundTrip(inv_kin, fwd_kin);
}

TEST(TesseractKinematicsUnit, TracIKInvKinUnit)  // NOLINT
{
  auto scene_graph = getSceneGraphIIWA();
  const KDLFwdKinChain fwd_kin(*scene_graph, BASE_LINK, TIP_LINK);

  const std::vector<TRAC_IK::SolveType> solve_types{
    TRAC_IK::SolveType::Speed, TRAC_IK::SolveType::Distance, TRAC_IK::SolveType::Manip1, TRAC_IK::SolveType::Manip2
  };

  for (const auto& solve_type : solve_types)
  {
    const TracIKInvKinChain inv_kin(
        *scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME, EPSILON, solve_type);
    expectSolvesRoundTrip(inv_kin, fwd_kin);
  }
}

TEST(TesseractKinematicsUnit, TracIKInvKinCloneUnit)  // NOLINT
{
  // A custom solver name is what makes the copy observable: one that failed to carry the name over reports the default
  // instead, which is what the source would have reported anyway
  const std::string custom_solver_name{ "CustomTracIKSolverName" };

  auto scene_graph = getSceneGraphIIWA();
  const KDLFwdKinChain fwd_kin(*scene_graph, BASE_LINK, TIP_LINK);
  const TracIKInvKinChain inv_kin(*scene_graph, BASE_LINK, TIP_LINK, custom_solver_name, TEST_MAX_TIME);

  // Both the copy and the clone rebuild the underlying solver rather than sharing it
  const TracIKInvKinChain copied(inv_kin);
  EXPECT_EQ(copied.getSolverName(), custom_solver_name);
  EXPECT_EQ(copied.getJointIds(), inv_kin.getJointIds());
  expectSolvesRoundTrip(copied, fwd_kin);

  const InverseKinematics::UPtr cloned = inv_kin.clone();
  ASSERT_TRUE(cloned != nullptr);
  EXPECT_EQ(cloned->getSolverName(), custom_solver_name);
  EXPECT_EQ(cloned->getJointIds(), inv_kin.getJointIds());
  expectSolvesRoundTrip(*cloned, fwd_kin);

  // Assigning over a chain built for a shorter chain must adopt the source chain, not keep the target's
  TracIKInvKinChain assigned(
      *scene_graph, BASE_LINK, LinkId("link_3"), TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);
  EXPECT_EQ(assigned.numJoints(), 3);
  assigned = inv_kin;
  EXPECT_EQ(assigned.numJoints(), 7);
  EXPECT_EQ(assigned.getTipLinkIds().front(), TIP_LINK);
  EXPECT_EQ(assigned.getSolverName(), custom_solver_name);
  expectSolvesRoundTrip(assigned, fwd_kin);
}

TEST(TesseractKinematicsUnit, TracIKInvKinBoundsUnit)  // NOLINT
{
  // Non-zero bounds relax the Cartesian tolerance a solution must satisfy, so the discriminating query is one that no
  // configuration can satisfy within epsilon: the tip fully extended, then pushed further out along the same ray. The
  // link offsets of this arm sum to 1.306 m, which is what it measures fully extended, so the reachable set cannot come
  // closer to the target than the overreach and no bound-free solve can succeed.
  auto scene_graph = getSceneGraphIIWA();
  const KDLFwdKinChain kdl_fwd_kin(*scene_graph, BASE_LINK, TIP_LINK);
  const ForwardKinematics& fwd_kin = kdl_fwd_kin;

  const double overreach = 0.03;
  Eigen::Isometry3d target_pose = fwd_kin.calcFwdKin(Eigen::VectorXd::Zero(7)).at(TIP_LINK);
  target_pose.translation().z() += overreach;

  const tesseract::common::LinkIdTransformMap input{ { TIP_LINK, target_pose } };
  const Eigen::VectorXd seed = Eigen::VectorXd::Zero(7);

  {  // The default bounds are all zero, which leaves epsilon in charge and rejects every configuration
    const TracIKInvKinChain trac_ik(*scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);
    const InverseKinematics& inv_kin = trac_ik;
    EXPECT_TRUE(inv_kin.calcInvKin(input, seed).empty());
  }

  {  // A bound wider than the overreach accepts the closest configuration instead
    const double linear_bound = 0.05;
    const double angular_bound = 0.1;
    const KDL::Twist bounds(KDL::Vector(linear_bound, linear_bound, linear_bound),
                            KDL::Vector(angular_bound, angular_bound, angular_bound));
    const TracIKInvKinChain trac_ik(*scene_graph,
                                    BASE_LINK,
                                    TIP_LINK,
                                    TRACIK_INV_KIN_CHAIN_SOLVER_NAME,
                                    TEST_MAX_TIME,
                                    EPSILON,
                                    SOLVE_TYPE,
                                    bounds);
    const InverseKinematics& inv_kin = trac_ik;

    const IKSolutions solutions = inv_kin.calcInvKin(input, seed);
    ASSERT_FALSE(solutions.empty());
    for (const auto& solution : solutions)
    {
      const Eigen::Isometry3d actual = fwd_kin.calcFwdKin(solution).at(TIP_LINK);
      expectPoseNear(target_pose, actual, std::sqrt(3.0) * linear_bound, std::sqrt(3.0) * angular_bound);

      // The solution is admissible only because of the bounds: the target is out of reach, so no configuration can
      // land closer to it than the overreach
      EXPECT_GT((target_pose.translation() - actual.translation()).norm(), 0.99 * overreach);
    }

    // Copies have to carry the bounds, or the same query stops being solvable through them
    const TracIKInvKinChain copied(trac_ik);
    EXPECT_FALSE(static_cast<const InverseKinematics&>(copied).calcInvKin(input, seed).empty());
    EXPECT_FALSE(trac_ik.clone()->calcInvKin(input, seed).empty());
  }
}

TEST(TesseractKinematicsUnit, TracIKInvKinJointLimitsUnit)  // NOLINT
{
  // The solver takes its joint limits from the scene graph, so narrowing one has to constrain the solutions
  auto scene_graph = getSceneGraphIIWA();
  auto joint_a1 = scene_graph->getJoint(JointId("joint_a1"));
  joint_a1->limits->lower = -0.3;
  joint_a1->limits->upper = 0.3;

  const KDLFwdKinChain kdl_fwd_kin(*scene_graph, BASE_LINK, TIP_LINK);
  const TracIKInvKinChain trac_ik(*scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);

  // The single-argument calcFwdKin and two-argument calcInvKin are only visible through the base interfaces
  const ForwardKinematics& fwd_kin = kdl_fwd_kin;
  const InverseKinematics& inv_kin = trac_ik;

  // The target is reachable inside the narrowed limit, but the seed sits well outside it: a solver that did not pick
  // up the narrowed limit would converge near the seed instead
  Eigen::VectorXd q_ref = getReferenceConfiguration();
  q_ref(0) = 0.0;
  const Eigen::Isometry3d target_pose = fwd_kin.calcFwdKin(q_ref).at(TIP_LINK);

  Eigen::VectorXd seed = q_ref;
  seed(0) = 2.0;

  const tesseract::common::LinkIdTransformMap input{ { TIP_LINK, target_pose } };
  const IKSolutions solutions = inv_kin.calcInvKin(input, seed);
  ASSERT_FALSE(solutions.empty());

  for (const auto& solution : solutions)
  {
    EXPECT_GE(solution(0), joint_a1->limits->lower);
    EXPECT_LE(solution(0), joint_a1->limits->upper);
    expectPoseNear(target_pose, fwd_kin.calcFwdKin(solution).at(TIP_LINK), 1e-3, 1e-3);
  }
}

TEST(TesseractKinematicsUnit, TracIKInvKinGroupUnit)  // NOLINT
{
  auto scene_graph = getSceneGraphIIWA();
  const tesseract::scene_graph::KDLStateSolver state_solver(*scene_graph);
  const tesseract::scene_graph::SceneState scene_state = state_solver.getState();

  auto inv_kin = std::make_unique<TracIKInvKinChain>(
      *scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);
  const std::vector<JointId> joint_ids = inv_kin->getJointIds();
  const KinematicGroup kin_group("manip", joint_ids, std::move(inv_kin), *scene_graph, scene_state);

  EXPECT_EQ(kin_group.getBaseLinkId(), scene_graph->getRoot());
  EXPECT_EQ(kin_group.getRedundancyCapableJointIndices(), std::vector<Eigen::Index>({ 0, 1, 2, 3, 4, 5, 6 }));

  // The group takes the target in the working frame rather than the chain base, so the round trip has to be expressed
  // relative to that frame as well
  const Eigen::VectorXd q_ref = getReferenceConfiguration();
  const tesseract::common::LinkIdTransformMap ref_poses = kin_group.calcFwdKin(q_ref);
  const Eigen::Isometry3d target_pose = ref_poses.at(BASE_LINK).inverse() * ref_poses.at(TIP_LINK);
  const Eigen::VectorXd seed = q_ref.array() + 0.1;

  const IKSolutions solutions = kin_group.calcInvKin(KinGroupIKInput(target_pose, BASE_LINK, TIP_LINK), seed);
  ASSERT_FALSE(solutions.empty());
  for (const auto& solution : solutions)
  {
    const tesseract::common::LinkIdTransformMap poses = kin_group.calcFwdKin(solution);
    expectPoseNear(target_pose, poses.at(BASE_LINK).inverse() * poses.at(TIP_LINK), 1e-3, 1e-3);
  }

  EXPECT_TRUE(checkKinematics(kin_group));

  EXPECT_ANY_THROW(  // NOLINT
      kin_group.calcInvKin(KinGroupIKInput(target_pose, LinkId("does_not_exist"), TIP_LINK), seed));
  EXPECT_ANY_THROW(  // NOLINT
      kin_group.calcInvKin(KinGroupIKInput(target_pose, BASE_LINK, LinkId("does_not_exist")), seed));
}

TEST(TesseractKinematicsUnit, TracIKInvKinUnreachablePoseUnit)  // NOLINT
{
  auto scene_graph = getSceneGraphIIWA();
  const TracIKInvKinChain inv_kin(*scene_graph, BASE_LINK, TIP_LINK, TRACIK_INV_KIN_CHAIN_SOLVER_NAME, TEST_MAX_TIME);

  Eigen::Isometry3d pose{ Eigen::Isometry3d::Identity() };
  pose.translation() = Eigen::Vector3d(5, 0, 0);

  const tesseract::common::LinkIdTransformMap input{ { TIP_LINK, pose } };
  IKSolutions solutions;
  inv_kin.calcInvKin(solutions, input, Eigen::VectorXd::Zero(7));
  EXPECT_TRUE(solutions.empty());
}

TEST(TesseractKinematicsUnit, TracIKInvKinConstructorFailuresUnit)  // NOLINT
{
  auto scene_graph = getSceneGraphIIWA();

  EXPECT_ANY_THROW(TracIKInvKinChain(*scene_graph, LinkId("does_not_exist"), TIP_LINK));   // NOLINT
  EXPECT_ANY_THROW(TracIKInvKinChain(*scene_graph, BASE_LINK, LinkId("does_not_exist")));  // NOLINT

  const tesseract::scene_graph::SceneGraph empty_scene_graph;
  EXPECT_ANY_THROW(TracIKInvKinChain(empty_scene_graph, BASE_LINK, TIP_LINK));  // NOLINT
}

int main(int argc, char** argv)
{
  testing::InitGoogleTest(&argc, argv);

  return RUN_ALL_TESTS();
}
